title: Clean up unused iOS simulators
summary: This step helps free up disk space by removing unused iOS simulators in Bitrise VMs.

website: https://github.com/bitrise-silver/simulator-cleanup
source_code_url: https://github.com/bitrise-silver/simulator-cleanup
support_url: https://github.com/bitrise-silver/simulator-cleanup/issues

type_tags:
- utility

run_if: .IsCI
is_skippable: true

toolkit:
  go:
    package_name: https://github.com/bitrise-silver/simulator-cleanup

inputs:
- remove_versions_lower_than: "0.0"
  opts:
    title: Remove simulators with lower-bound versions
    summary: Remove simulators with versions lower than this parameter value
    is_required: false

- remove_versions_higher_than: "99.0"
  opts:
    title: Remove simulators with upper-bound versions
    summary: Remove simulators with versions lower than this parameter value
    is_required: false

- platform: "iOS"
  opts:
    title: Remove simulators with specified platform
    summary: Remove simulators with specified platform
    is_required: false